### ISSUE TITLE
[Feature Request] Single overarching tool

### ISSUE THREAD

**Issue by beasteers** [dnephin/compose-addons#10]
I just came across this package and it seems like an awesome tool!

A super useful feature would be a single command that sits atop the other addons and runs them as needed. 

Then it would be as simple as:
```bash
dcao up -d
```
So for example, if you had:

```yaml
# A.yml
include:
 - ../B.dev.yml
 - ../C.yml

# B.dev.yml
merge: B.yml

# B.yml
namespace: B

# C.yml
namespace: C
```
It would perform all addon actions required to make it valid docker-compose.

And it could work with any docker-compose command (`down`, `build`, etc) and just run the compilation step beforehand. I'm sure there are ways of caching that could provide speedup as well.
